const POLICE_COLORS = ["#2aff50", "#00c1d0", "#559dff"]
const AMBULANCE_COLORS = ["#dbe900", "#e37500", "#b12c00"]
const FIRE_BRIGADE_COLORS = ["#2e00bf", "#8815ff", "#ef00ff"]
const HELICOPTER_COLORS = ["#ff8cc6", "#ffac81", "#de369d"]

export default {
  POLICE_COLORS: POLICE_COLORS,
  AMBULANCE_COLORS: AMBULANCE_COLORS,
  FIRE_BRIGADE_COLORS: FIRE_BRIGADE_COLORS,
  HELICOPTER_COLORS: HELICOPTER_COLORS,
}
